quotas_default:
  resources:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"

namespaces:
  jump-app-dev-01:
    networkpolicy:
      enabled: true
    quotas:
      enabled: true
      resources:
        secrets: "10"
        services: "10"
        services.loadbalancers: "2"
  jump-app-dev-02:
    quotas:
      enabled: true
    networkpolicy:
      enabled: true
  jump-app-dev-03: 
    quotas:
      enabled: false
    networkpolicy:
      enabled: false

networking:
  allow-dev02-dev01:
    orig: jump-app-dev-02
    dest: jump-app-dev-01

argocd:
  enabled: true
  controller: openshift-gitops