namespaces:
  jump-app-pre-ab01:
    networkpolicy:
      enabled: true
    quotas:
      enabled: true
  jump-app-pre-ab02:
    quotas:
      enabled: true
    networkpolicy:
      enabled: true

networking:
  allow-ab02-ab01:
    orig: jump-app-pre-ab02
    dest: jump-app-pre-ab01

argocd:
  enabled: true
  controller: openshift-gitops